%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 720
image_height: 1280
distortion_parameters:
   k1: 0.0478
   k2: 0.0339
   p1: -0.00033
   p2: -0.00091
projection_parameters:
   fx: 1077.2
   fy: 1079.3
   cx: 362.145
   cy: 636.3873

