%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 720
image_height: 1280
distortion_parameters:
   k1: 0.0366
   k2: 0.0803
   p1: 0.000783
   p2: -0.000215
projection_parameters:
   fx: 1082.4
   fy: 1084.4
   cx: 364.6778
   cy: 643.3080

